apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: opencart
  name: opencart
spec:
  type: {{ .Values.apacheService.type }}
  ports:
    - name: http
      port: 80
      targetPort: http
      {{- if .Values.apacheService.nodePort }}
      nodePort: {{ .Values.apacheService.nodePort }}
      {{- end }}
  selector:
    io.kompose.service: opencart